# Generated by Django 3.2.5 on 2021-07-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0003_auto_20210722_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='board',
        ),
    ]
