# Generated by Django 3.2.5 on 2021-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0003_board_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='file_path',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
