# Generated by Django 3.2.5 on 2021-07-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0004_auto_20210719_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
